### ISSUE TITLE
Not able to connect with the Backend Supapbase

### ISSUE THREAD

**Issue by vishaltalreja01** [j471n/j471n.in#25]
Hello Jatin, I just downloaded the repository and installed all mandatory packages but I am not Not able to connect with the Backend Supaphase and also apis.
I am getting this "Something went wrong. I know you don't know what's the problem. So Let me know by [creating an issue](https://github.com/j471n/j471n.in/issues/new) on GitHub." error.

**Comment by j471n** [comment]
Could you just provide the logs and few more details like in what stage are you getting the error in supabase. Also have you configured the Supabase it's policies and all?

**Comment by vishaltalreja01** [comment]
Yes I have configured the Supabase policies, I am not able to setup my Supabase because the guidance is not available in your dev.blog.

**Comment by j471n** [comment]
You can check [this](https://github.com/j471n/j471n.in#documentation:~:text=Supabase%20Integration%3A) guide it might help. If you can provide more info that would be good to know what's the actual issue that you are facing.

**Comment by vishaltalreja01** [comment]
![image](https://github.com/j471n/j471n.in/assets/85024054/1aec5daf-e2cc-47f3-be55-129f3880fc12)
![image](https://github.com/j471n/j471n.in/assets/85024054/91acc90b-b66d-462a-8a9f-3c0336c2261b)

**Comment by vishaltalreja01** [comment]
can you please rec a video to setup the whole Supabase and Sanity.io with tables, schemas also

**Comment by j471n** [comment]
It seems like you have some issue with the schema of Supabase. Currently it's not possible for me to record a video to setup this. [This discussion](https://github.com/j471n/j471n.in/discussions/22#discussioncomment-5165783) should guide you to have the exact columns in the table.

**Comment by vishaltalreja01** [comment]
I followed that Discussion after that the tables and data is inputed in the Supabase but still showing that error in project and certificate page

**Comment by j471n** [comment]
You see there is a function called `getCertificates` in that we are return error as well so try to console that error. It should have some message.

**Comment by vishaltalreja01** [comment]
![image](https://github.com/j471n/j471n.in/assets/85024054/e8d88cf5-f64c-492c-a055-6f1de1dd8329)
![image](https://github.com/j471n/j471n.in/assets/85024054/ed75e842-c169-442f-8df2-48e04d873528)

**Comment by vishaltalreja01** [comment]
can you get into my pc to resolve this issue?

**Comment by vishaltalreja01** [comment]
through Anydesk or Teamviewer?

**Comment by therockstarind** [comment]
> ![image](https://user-images.githubusercontent.com/85024054/267651057-e8d88cf5-f64c-492c-a055-6f1de1dd8329.png) ![image](https://user-images.githubusercontent.com/85024054/267652197-5a955a8c-0a86-4cf0-a92d-d5ecfddc2c47.png)

  **Add Type of these in Database**
  id
  title
  issuedDate
  orgName
  orgLogo
  url
  pinned
  
  **in your database all are the text type**

**Comment by j471n** [comment]
> can you get into my pc to resolve this issue?
> through Anydesk or Teamviewer?

I can do it, however my this and next weekend schedule it pretty tight. So it's hard for me to connect with you. Maybe you can connect with @therockstarind He might guide you cause he also configured this.

**Comment by vishaltalreja01** [comment]
@therockstarind hello dear, can you connect with my pc and help me resolve the issues please

**Comment by therockstarind** [comment]
> @therockstarind hello dear, can you connect with my pc and help me resolve the issues please

I will try at night 🌙

**Comment by vishaltalreja01** [comment]
are you available now?
